# build react for prod
FROM node:12

WORKDIR /usr/src/app

ENV NODE_ENV production

RUN npm install --silent

RUN npm install react-scripts -g --silent

COPY . .

RUN npm run build

# spin up prod environment
FROM nginx:1.13.12-alpine

COPY --from=build /usr/src/app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]